[workspace]
members = [
    "game",
    "playground",
    "player",
    "test_server",
    "test_client", "azul",
]
resolver = "2"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = true
