
[game]
num_games = 50
num_simultaneous_games = 10
verbose = false
constant_ordering = false

[player_one]
executable = "./target/release/test_client.exe"
think_time = 2500

[player_two]
executable = "./clients/2/2.exe"
think_time = 2500

# [player_three]
# executable = "./target/release/test_client.exe"
# think_time = 1000

# [player_four]
# executable = "./target/release/test_client.exe"
# think_time = 1000
