[game]
num_games = 250
num_simultaneous_games = 10
constant_ordering = false
verbose = false
[player_one]
executable = "target/release/test_client.exe"
think_time = 1500
[player_two]
executable = "clients/2/6.exe"
think_time = 1500
