
[game]
num_games = 100
num_simultaneous_games = 7

[player_one]
executable = "./target/release/test_client.exe"
think_time = 400

[player_two]
executable = "./clients/test_client-2.exe"
think_time = 400
