
[game]
num_games = 200
num_simultaneous_games = 10
verbose = false

[player_one]
executable = "./target/release/test_client.exe"
think_time = 450

[player_two]
executable = "./clients/3/test_client-10.exe"
think_time = 450

[player_three]
executable = "./clients/3/test_client-10.exe"
think_time = 450

# [player_four]
# executable = "./target/release/test_client.exe"
# think_time = 450
