[game]
num_games = 100
num_simultaneous_games = 10
constant_ordering = false
verbose = false
[player_one]
executable = "target/release/test_client.exe"
think_time = 10000
[player_two]
executable = "clients/2/10.exe"
think_time = 10000
