
[game]
num_games = 200
num_simultaneous_games = 2
verbose = false

[player_one]
executable = "./target/release/test_client.exe"
think_time = 450

[player_two]
executable = "./clients/no-ponder.exe"
think_time = 450
