
[game]
num_games = 1000
num_simultaneous_games = 7
verbose = false

[player_one]
executable = "./target/release/test_client.exe"
think_time = 400

[player_two]
executable = "./clients/test_client-3.exe"
think_time = 400
