
[game]
alternate_starting_player = true
num_games = 100
num_simultaneous_games = 4

[player_one]
executable = "./target/release/test_client.exe"
think_time = 1600

[player_two]
executable = "./target/release/test_client.exe"
think_time = 600
