[game]
num_games = 250
num_simultaneous_games = 10
constant_ordering = false
verbose = false
[player_one]
executable = "target/release/test_client.exe"
think_time = 2000
[player_two]
executable = "target/release/test_client.exe"
think_time = 20000
