[package]
name = "player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game = { path = "../game" }
rand = { version = "0.8.5", features = ["small_rng"] }
async-trait = "0.1.51"
